# Generated by Django 6.0.5 on 2026-05-28 03:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('nik', models.CharField(blank=True, max_length=16)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], default='L', max_length=1)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=15)),
                ('alamat', models.TextField(blank=True)),
                ('jenis_pasien', models.CharField(choices=[('umum', 'Umum'), ('bpjs', 'BPJS')], default='umum', max_length=10)),
            ],
            options={
                'verbose_name': 'Pasien',
                'verbose_name_plural': 'Pasien',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Poliklinik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=2, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('ruangan', models.CharField(default='Ruang 1', max_length=20)),
                ('dokter', models.CharField(blank=True, max_length=100)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Poliklinik',
                'verbose_name_plural': 'Poliklinik',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='Antrian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pasien', models.CharField(max_length=150)),
                ('nik', models.CharField(blank=True, max_length=16)),
                ('jenis_pasien', models.CharField(choices=[('umum', 'Umum'), ('bpjs', 'BPJS')], default='umum', max_length=10)),
                ('keluhan', models.TextField(blank=True)),
                ('nomor_urut', models.PositiveIntegerField()),
                ('kode_antrian', models.CharField(max_length=10)),
                ('tanggal', models.DateField(default=django.utils.timezone.localdate)),
                ('waktu_daftar', models.DateTimeField(auto_now_add=True)),
                ('waktu_panggil', models.DateTimeField(blank=True, null=True)),
                ('waktu_selesai', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('dipanggil', 'Dipanggil'), ('dilayani', 'Sedang Dilayani'), ('selesai', 'Selesai'), ('batal', 'Batal / Tidak Hadir')], default='menunggu', max_length=15)),
                ('catatan_dokter', models.TextField(blank=True)),
                ('pasien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='antrian.pasien')),
                ('poliklinik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antrian.poliklinik')),
            ],
            options={
                'verbose_name': 'Antrian',
                'verbose_name_plural': 'Antrian',
                'ordering': ['tanggal', 'poliklinik', 'nomor_urut'],
                'unique_together': {('poliklinik', 'tanggal', 'nomor_urut')},
            },
        ),
    ]
